<h2>Cart</h2>
<?php if (count($books) == 0): ?>
<p>Your cart is empty.</p>
<?php else: ?>
<?php $total = 0; ?>
<form action="<?= ROOT_URL ?>/cart" method="post">
    <table class="books">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>ISBN</th>
            <th>Stock</th>
            <th>Price</th>
            <th>Course(s):</th>
            <th>Quantity</th>
        </tr>
    <?php foreach($books as $book): ?>
        <tr>
            <td><?= $book->title ?></td>
            <td><?= str_replace(', ', '<br />', $book->authors) ?></td>
            <td><?= sprintf("%s-%s-%s-%s-%s", substr($book->isbn, 0, 3), substr($book->isbn, 3, 1), substr($book->isbn, 4, 2), substr($book->isbn, 6, 6), substr($book->isbn, 12, 1)) ?></td>
            <td>In-Stock</td>
            <td>$<?= sprintf("%d.%02d", $book->price / 100, $book->price % 100) ?></td>
            <td><?= str_replace(', ', '<br>', $book->courses) ?></td>
            <td>
                <center>
                    <input type="text" name="book_quantities[]" value="<?= $book->quantity ?>" style="width: 2em;">
                </center>
            </td>
        </tr>
        <?php $total += $book->price; ?>
    <?php endforeach; ?>
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <td colspan="2">Subtotal: $<?= sprintf("%d.%02d", $total / 100, $total % 100) ?></td>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
    </table>
    <input style="overflow: visible !important; height: 0 !important; width: 0 !important; margin: 0 !important; border: 0 !important; padding: 0 !important; display: block !important;" type="submit" name="cart_quantities">
    <div class="form_buttons"><input type="submit" name="cart_empty" value="Empty cart"> <input type="submit" name="cart_quantities" value="Update Quantities"></div>
    <fieldset>
        <legend>Student Details</legend>
        <label for="student_number">Student Number:</label> <input type="text" name="student_number" id="student_number"><br>
        <input type="submit" name="order" value="Place Order">
    </fieldset>
</form>
<?php endif; ?>