<h2>Cart</h2>
<?php if (count($books) == 0): ?>
<p>Your cart is empty.</p>
<?php else: ?>
<form action="<?= ROOT_URL ?>/cart" method="post">
    <table class="books">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>ISBN</th>
            <th>Stock</th>
            <th>Price</th>
            <th>Course(s):</th>
            <th>Quantity</th>
        </tr>
    <?php foreach($books as $book): ?>
        <tr>
            <td><?= $book->title ?></td>
            <td><?= str_replace(', ', '<br />', $book->authors) ?></td>
            <td><?= sprintf("%s-%s-%s-%s-%s", substr($book->isbn, 0, 3), substr($book->isbn, 3, 1), substr($book->isbn, 4, 2), substr($book->isbn, 6, 6), substr($book->isbn, 12, 1)) ?></td>
            <td>In-Stock</td>
            <td>$<?= sprintf("%d.%02d", $book->price / 100, $book->price % 100) ?></td>
            <td><?= str_replace(', ', '<br>', $book->courses) ?></td>
            <td>
                <center>
                    <input type="text" name="book_quantities[]" value="<?= $book->quantity ?>" style="width: 2em;">
                </center>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <div class="form_buttons"><input type="submit" name="cart_empty" value="Empty cart"> <input type="submit" name="cart_quantities" value="Update Quantities"></div>
    <div class="form_buttons"><input type="submit" name="order" value="Place Order"></div>
</form>
<?php endif; ?>