<h2>Books</h2>

<h3>Add or Update Book</h3>
<p>If the given ISBN does not already exist, a new book record will be created. Otherwise, the title and price of the existing record will be updated.</p>
<form action="<?= ROOT_URL ?>/management" method="post">
    <label for="add_isbn">ISBN:</label>
    <input type="text" name="isbn" id="add_isbn"><br>
    <label for="add_title">Title:</label>
    <input type="text" name="title" id="add_title"><br>
    <label for="add_price">Price:</label>
    <input type="text" name="price" id="add_price"><br>
    <input type="submit" name="manage_add" value="Add Book">
</form>

<h3>Update Book Stock</h3>
<form action="<?= ROOT_URL ?>/management" method="post">
    <label for="stock_isbn">ISBN:</label>
    <input type="text" name="isbn" id="stock_isbn"><br>
    <label for="stock_quantity">Quantity:</label>
    <input type="text" name="quantity" id="stock_quantity"><br>
    <input type="submit" name="manage_stock" value="Update Stock">
</form>

<h3>Update Book Stockability</h3>
<p>Books which are not stocked are not visible outside of the staff interface and may not be ordered.</p>
<form action="<?= ROOT_URL ?>/management" method="post">
    <label for="stocked_isbn">ISBN:</label>
    <input type="text" name="isbn" id="stocked_isbn"><br>
    <label for="stocked_state">Stockability:</label>
    <select name="stocked" id="stocked_state">
        <option value="true">Stocked</option>
        <option value="false">Not Stocked</option>
    </select><br>
    <input type="submit" name="manage_stocked" value="Update Stockability">
</form>

<hr>

<h2>Authors</h2>

<h3>Add Author</h3>
<form action="<?= ROOT_URL ?>/management" method="post">
    <label for="author_given_name">Given name:</label>
    <input type="text" name="given_name" id="author_given_name"><br>
    <label for="author_family_name">Family name:</label>
    <input type="text" name="family_name" id="author_family_name"><br>
    <input type="submit" name="manage_author_add" value="Add Author">
</form>

<h3>Remove Author</h3>
<form action="<?= ROOT_URL ?>/management" method="post">
    <label for="remove_author">Author:</label>
    <select name="author_id" id="remove_author">
        <?php foreach($authors as $author): ?>
        <option value="<?= $author->author_id ?>"><?= $author->sort_name ?></option>
        <?php endforeach; ?>
    </select><br>
    <input type="submit" name="manage_author_remove" value="Remove Author">
</form>

<h3>Associate Author with Book</h3>
<form action="<?= ROOT_URL ?>/management" method="post">
    <label for="book_author_isbn">ISBN:</label>
    <input type="text" name="isbn" id="book_author_isbn"><br>
    <label for="book_author">Author:</label>
    <select name="author_id" id="book_author">
        <?php foreach($authors as $author): ?>
        <option value="<?= $author->author_id ?>"><?= $author->sort_name ?></option>
        <?php endforeach; ?>
    </select><br>
    <input type="submit" name="manage_book_author_add" value="Add Author to Book">
    <input type="submit" name="manage_book_author_remove" value="Remove Author from Book">
</form>

<hr>

<h2>Sections</h2>

<h3>Associate Book with Section</h3>
<form action="<?= ROOT_URL ?>/management" method="post">
    <label for="book_section_isbn">ISBN:</label>
    <input type="text" name="isbn" id="book_section_isbn"><br>
    <label for="book_section">Section:</label>
    <select name="section_number" id="book_section">
        <?php foreach($sections as $section): ?>
        <option value="<?= $section->section_number ?>"><?= $section->department_code ?> <?= $section->course_number ?> <?= $section->slot ?></option>
        <?php endforeach; ?>
    </select><br>
    <input type="submit" name="manage_book_section_add" value="Add Book to Section">
    <input type="submit" name="manage_book_section_remove" value="Remove Book from Section">
</form>