<h2>Outstanding Orders</h2>
<?php if (count($orders) == 0): ?>
<p>No outstanding orders.</p>
<?php else: ?>
<table class="books">
    <tr>
        <th>Order ID</th>
        <th>Date Placed</th>
        <th>Fulfill</th>
    </tr>
<?php foreach($orders as $order): ?>
    <tr>
        <td><a href="<?= ROOT_URL ?>/order/<?= $order->order_id ?>"><?= $order->order_id ?></a></td>
        <td><?= $order->order_date ?></td>
        <td><form action="<?= ROOT_URL ?>/orders" method="post"><input type="hidden" name="order_id" value="<?= $order->order_id ?>"><input type="submit" name="order_fulfill" value="Fulfill"></form></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<h2>Fulfilled Orders</h2>
<?php if (count($fulfilled_orders) == 0): ?>
<p>No fulfilled orders.</p>
<?php else: ?>
<table class="books">
    <tr>
        <th>Order ID</th>
        <th>Date Placed</th>
        <th>Date Fulfilled</th>
    </tr>
<?php foreach($fulfilled_orders as $order): ?>
    <tr>
        <td><a href="<?= ROOT_URL ?>/order/<?= $order->order_id ?>"><?= $order->order_id ?></a></td>
        <td><?= $order->order_date ?></td>
        <td><?= $order->arrival_date ?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif; ?>